<!-- begin cities list -->

<div id="cities_list">
<table>
  <tr>
    <td colspan="2"><div id="cities_list_header">Take me there...</div></td>
  </tr>
  <tr>
    <th colspan="2">UK</th>
  </tr>

  <tr>
    <td><a href="http://birmingham.openguides.org/">Birmingham</a></td>
    <td><a href="http://miltonkeynes.openguides.org/">Milton Keynes</a></td>
  </tr>
  <tr>
    <td><a href="http://cambridge.openguides.org/">Cambridge</a></td>
    <td><a href="http://north-devon.openguides.org/">North Devon</a></td>

  <tr>
    <td><a href="http://cotswolds.openguides.org/">Cotswolds</a></td>
    <td><a href="http://norwich.openguides.org/">Norwich</a></td>
  </tr>
  <tr>
    <td><a href="http://glasgow.openguides.org/">Glasgow</a></td>
    <td><a href="http://nottingham.openguides.org/">Nottingham</a></td>

  </tr>
  <tr>
    <td><a href="http://lancaster.openguides.org/">Lancaster</a></td>
    <td><a href="http://oxford.openguides.org/">Oxford</a></td>
  </tr>
  <tr>
    <td><a href="http://london.openguides.org/">London</a></td>

    <td><a href="http://the.earth.li/~kake/cgi-bin/openguides/vegan-oxford.cgi">Vegan Oxford</a></td>
  </tr>
  <tr>
    <td><a href="http://london.randomness.org.uk/">Randomness (London)</a></td>
    <td><a href="http://reading.openguides.org/">Reading</a></td>
  </tr>
  <tr>

    <td><a href="http://manchester.openguides.org/">Manchester</a></td>
    <td><a href="http://southampton.openguides.org/">Southampton</a></td>
  </tr>
  <tr>
    <th>Canada</th>

    <th>Europe</th>
  </tr>
  <tr>
    <td><a href="http://montreal.openguides.org/">Montreal, QC</a></td>
    <td><a href="http://www.justbiit.com/cgi-bin/openguides/">Brussels</a></td>
  </tr>
  <tr>

  <td><a href="http://victoria.openguides.org/">Victoria, BC</a></td>
    <td><a href="http://vienna.openguides.org/">Vienna</a></td>
  </tr>
  <tr>
    <th>USA</th>
    <th>Worldwide</th>
  </tr>

  <tr>
    <td><a href="http://boston.openguides.org/">Boston, MA</a></td>
    <td><a href="http://engineer.openguides.org/">Tourist Engineer</a></td>
  </tr>
  <tr>
    <td><a href="http://saintpaul.openguides.org/">Saint Paul, MN</a></td>
  </tr>

  <tr>
    <td><a href="http://newyork.openguides.org/">New York, NY</a></td>
  </tr>
</table>
</div>

<!-- end cities list -->