<!-- begin cities list -->

<div id="cities_list">
<table>
  <tr>
    <td colspan="2"><div id="cities_list_header">Take me there...</div></td>
  </tr>
  <tr>
    <th colspan="2">UK</th>
  </tr>

  <tr>
    <td><a href="http://cambridge.openguides.org/">Cambridge</a></td>
    <td><a href="http://oxford.openguides.org/">Oxford</a></td>
  </tr>
  <tr>
    <td><a href="http://cotswolds.openguides.org/">Cotswolds</a></td>
    <td><a href="http://the.earth.li/~kake/cgi-bin/openguides/vegan-oxford.cgi">Vegan Oxford</a></td>
  </tr>
  <tr>
    <td><a href="http://london.randomness.org.uk/">Randomness (London)</a></td>
    <td><a href="http://reading.openguides.org/">Reading</a></td>
  </tr>
  <tr>
    <td><a href="http://miltonkeynes.openguides.org/">Milton Keynes</a></td>
    <td><a href="http://southampton.openguides.org/">Southampton</a></td>
  </tr>
  <tr>
    <td><a href="http://north-devon.openguides.org/">North Devon</a></td>
    <td></td>
  </tr>

  <tr>
    <th>Europe</th>
    <th></th>
  </tr>
  <tr>
    <td><a href="http://www.justbiit.com/cgi-bin/openguides/">Brussels</a></td>
    <td></td>
  </tr>
  <tr>
    <td><a href="http://cern.openguides.org/">CERN</a></td>
    <td></td>
  </tr>

</table>
</div>

<!-- end cities list -->
