 	
<!-- begin footer -->
 	<div id="footer">
 		<div id="freeourdata">
		 	<a href="http://www.freeourdata.org.uk/" title="Free Our Data: Make taxpayers' data available to them.">
		 	<img id="freeimg" src="img/freeourdata.gif"
		 	 alt="Free Our Data: Make taxpayers' data available to them. http://www.freeourdata.org.uk/"></a>
 		</div>
 		
 		<div id="freethepostcode">
		 	<a href="http://www.freethepostcode.org/">FREE THE POSTCODE!</a>
 		</div>
	</div>  

	 	
 	<div id="trademarks">
		 <em>OpenGuides</em>, <em>[The] Open Guide
		 to...</em> and <em>the guides made by you</em> are
		 trademarks of The OpenGuides Project, copyright &copy;2002-2009. All rights
		 reserved.<br>
		 Trademarks used on member sites of the OpenGuides network by permission.
         Contact: <a href="mailto:contact@openguides.org">contact@openguides.org</a>
	</div>
 
<!--  end footer -->


