
 	<div id="header"> 
 		<a href="http://openguides.org/"><img src="img/logo.png" width="360" height="120" 
 		alt="OpenGuides: the guides made by you"></a>
 	</div>
	
	<div id="centeringdivforie">
  	 <div class="menu">
	
	<!-- Navigation menu -->
	
		<ul>
			<li>
				<a class="hide" href="index.html">Home</a>
				
				<!--[if lte IE 6]>
				<a href="index.html">Home</a>
				<![endif]-->				
			</li>
			
			
			<li>
				<a class="hide" href="information.html">Project</a>

				<!--[if lte IE 6]>
				<a href="project.html">Project<table><tr><td>
				<![endif]-->

				<ul>
					<li><a href="news.html">News Archive</a></li>
					<li><a href="lists.html">MailingLists</a></li>
					<li><a href="irc.html">IRC Channel</a></li>
					<li><a href="branding.html">Branding Guidelines</a></li>
				</ul>				

				<!--[if lte IE 6]>
				</td></tr></table></a>
			        <![endif]-->

				
			</li>
			<li><a class="hide" href="software.html">Software</a>
			
				<!--[if lte IE 6]>
				<a href="software.html">Software<table><tr><td>
				<![endif]-->			
		
				<ul>
					<li><a href="release_notes.html">Release Notes</a></li>
					<li><a href="search_help.html">Search Help</a></li>
					<li><a href="text_formatting.html">Text Formatting Help</a></li>
				</ul>
	
				<!--[if lte IE 6]>
				</td></tr></table></a>
		    	<![endif]-->		
    
			</li>	
		</ul>

 	 </div>
 	</div>
						<!-- end header --> 	
 	




