
 	<div id="header"> 
 		<a href="."><img src="img/logo.png" width="360" height="120" 
 		alt="OpenGuides: the guides made by you"></a>
 	</div>
	
	<div id="centeringdivforie">
  	 <div class="menu">
	
	<!-- Navigation menu -->
	
		<ul>
			<li>
				<a class="hide" href=".">Home</a>
				
				<!--[if lte IE 6]>
				<a href=".">Home</a>
				<![endif]-->				
			</li>
			
			
			<li>
				<a class="hide" href="information">Project</a>

				<!--[if lte IE 6]>
				<a href="project">Project<table><tr><td>
				<![endif]-->

				<ul>
					<li><a href="news">News Archive</a></li>
					<li><a href="lists">MailingLists</a></li>
					<li><a href="irc">IRC Channel</a></li>
					<li><a href="branding">Branding Guidelines</a></li>
				</ul>				

				<!--[if lte IE 6]>
				</td></tr></table></a>
			        <![endif]-->

				
			</li>
			<li><a class="hide" href="software">Software</a>
			
				<!--[if lte IE 6]>
				<a href="software">Software<table><tr><td>
				<![endif]-->			
		
				<ul>
					<li><a href="release_notes">Release Notes</a></li>
					<li><a href="search_help">Search Help</a></li>
					<li><a href="text_formatting">Text Formatting Help</a></li>
				</ul>
	
				<!--[if lte IE 6]>
				</td></tr></table></a>
		    	<![endif]-->		
    
			</li>	
		</ul>

 	 </div>
 	</div>
						<!-- end header --> 	
 	




