<!-- begin latest_news -->

<div class="news_date">
August 27, 2012
</div>

<p>Version 0.70 of OpenGuides was released yesterday.  The changes
include an upgrade to version 0.4 of the Leaflet mapping library; this
was done in order to allow use of <a
href="https://github.com/shramov/leaflet-plugins">Pavel Shramov's
Leaflet plugins</a> (in particular, the Google satellite view plugin
used on <a href="http://croydon.randomness.org.uk/">the Completists'
Guide to Croydon</a>).</p>

<p>The other main changes are to do with formatting and display of
node content.  External links are now given a class of "external",
rather than being formatted with hardcoded square brackets.  New
elements are allowed in page content: span, dl, dt, and dd.  Finally,
a new macro has been added &#8212; @INDEX_LIST_NO_PREFIX &#8212; which
gives a list of things in a given category or locale but leaves off
the "Category" or "Locale" prefix for any subcategories/sublocales in
that list.</p>

<!-- end latest_news -->
