<!-- begin latest_news -->

<div class="news_date">
August 19, 2008
</div>

<p>Apologies for the long delay since the last bit of news here; we
<i>were</i> doing things, honest, but because of the way the website was set
up, it was a faff to update.  This has now been fixed!</p>

<p>In other exciting news, we're having another hackfest!  It'll be in <a
href="http://oxford.openguides.org/">Oxford</a> this time, on Saturday 18
October and Sunday 19 October 2008.  Many more details can be found <a
href="http://dev.openguides.org/wiki/OxfordHackfest2008">on our dev wiki</a>.
</p>

<!-- end latest_news -->
