<!-- begin latest_news -->

<div class="news_date">
May 7, 2012
</div>

<p>Version 0.67 of OpenGuides was released today, with several major
changes and bugfixes.</p>

<p>We now use <a href="http://leaflet.cloudmade.com/">Leaflet</a> as
our JavaScript mapping library, with OpenStreetMap and MapQuest tiles
as default.  JSON output has been added or improved on several types
of pages, including index pages and user preferences.  A basic
stylesheet is now included in the distribution, and a long-standing
recent changes bug has been fixed.  Finally, it's now possible to
index on category and locale at the same time (so you can view e.g. a
list or map of all pubs in Holborn).</p>

<!-- end latest_news -->
